blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostListView2,
    #PostDetailView,
    #PostCreateView,
    PostUpdateView,
    #PostDeleteView,
    UserPostListView,
)
from . import views
import re

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    #path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    #path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    #path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

codingclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import PostListView


admin.site.site_header = "Coding Club NITJ"
admin.site.site_title = "Coding Club NITJ Portal"
admin.site.index_title = "Welcome to Coding Club NITJ Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls', namespace='authenticate')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tag/(?P<slug>[\w-]+)/$', PostListView.as_view(), name='tagged'),
    path('startup/', include('startup.urls', namespace='startup')),
    path('codearena/', include('codearena.urls', namespace='codearena')),
    path('meeting/', include('meeting.urls', namespace='meeting')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startup/urls.py
from django.urls import path
from . import views
from .views import PostUpdateView, UserPostListView

app_name = 'startup'
urlpatterns = [
	path('', views.home, name='home'),
	path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
]

startup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Idea(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100, null=True, blank=True)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

class Comment_Idea(models.Model):
	idea = models.ForeignKey(Idea, on_delete=models.CASCADE, related_name='comments_idea')
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	created = models.DateTimeField(default=timezone.now)
	Parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies_idea')

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return self.body

startup/forms.py
from django import forms
from .models import Comment_Idea, Idea
from pagedown.widgets import PagedownWidget


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment_Idea
		fields = ('body',)

	body = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Comment'}))
    

class PostForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Idea
        fields = ('title', 'content',)

startup/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Idea, Comment_Idea
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy


def home(request):
    posts = Idea.objects.all()
    posts = posts[::-1]
    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }
    return render(request, 'startup/home.html', context)

def post_detail(request, pk):
    object = get_object_or_404(Idea, pk=pk)
    comments = object.comments_idea.filter(Parent__isnull=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            Parent_obj = None
            try:
                Parent_id = int(request.POST.get('Parent_id'))
            except:
                Parent_id = None
            if Parent_id:
                Parent_obj = Comment_Idea.objects.get(id=Parent_id)
                if Parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.Parent = Parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.post = object
            new_comment.author = request.user
            new_comment.save()
            return redirect('startup:post-detail', object.id)
            
    else:
        comment_form = CommentForm()


    return render(request, 'startup/post_detail.html', {'object': object, 'comments': comments, 'comment_form': comment_form})

@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        form.save_m2m()
        # message success
        #messages.success(request, "Successfully Created")
        return redirect('startup:home')
    context = {
        "form": form,
    }
    return render(request, "startup/post_form.html", context)

class UserPostListView(ListView):
    model = Idea
    template_name = 'startup/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Idea
    fields = ['title', 'content']
    success_url = reverse_lazy('startup:home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        idea = self.get_object()
        if self.request.user == idea.author:
            return True
        return False

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Idea, pk=pk)
    post.delete()
    return redirect('startup:home')

startup/templates/startup/home.html
{% extends 'core/base.html' %}

{% block content %}
<br>
<div class="container" style="padding-top: 120px;">
  <h5>Click on this button: <a href="{% url 'startup:post-create' %}" class="btn-get-started" style="background-color: #EA4335; padding: 5px;">Submit Idea <i class="fa fa-lightbulb-o" aria-hidden="true"></i></a></h5><br>
  <h1>Recent Ideas Submitted</h1><hr>
  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'startup:user-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'startup:post-detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content content-markdown">{{ post.content }}</p>
      </div>
    </article>
    <hr>
    {% empty %}
    <h3>No ideas have been submitted yet.</h3>
  {% endfor %}

{% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

<br>
{% endblock content %}

startup/templates/startup/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container" style="padding-top: 150px;">
  <article class="media content-section">
    <img class="rounded-circle article-img" style="width: 75px; height: 75px;" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'startup:user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'startup:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'startup:post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content content-markdown">{{ object.content }}</p>
    </div>

  </article>
    {% if user.is_authenticated %}
      <h3>Add comment</h3>
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button class="btn btn-outline-info" type="submit">Add comment</button>
      </form>
    {% endif %}
<hr>
    {% for comment in comments %}
    <article class="media content-section">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'startup:user-posts' object.author.username %}">{{ comment.author }}</a>
        <small class="text-muted">{{ comment.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ comment.body | linebreaks }}</p>
</div></article>
      {% for reply in comment.replies.all %}
      <article class="media content-section" style="margin-left: 20px;">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'startup:user-posts' object.author.username %}">{{ reply.author }}</a>
        <small class="text-muted">{{ reply.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ reply.body | linebreaks }}</p>
</div></article>{% endfor %}

      {% if user.is_authenticated %}
      <div style="margin-left: 20px;">
      <h3>Reply</h3>
      
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="hidden" name="Parent_id", value="{{ comment.id }}">
        <button class="btn btn-outline-info" type="submit">Reply</button>
      </form>
    </div>
      {% endif %}
<hr>
    {% empty %}
    <p>There are no comments...</p>
    {% endfor %}
{% endblock content %}