blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostListView2,
    #PostDetailView,
    #PostCreateView,
    PostUpdateView,
    #PostDeleteView,
    UserPostListView,
)
from . import views
import re

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    #path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    #path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    #path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

codingclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import PostListView


admin.site.site_header = "Coding Club NITJ"
admin.site.site_title = "Coding Club NITJ Portal"
admin.site.index_title = "Welcome to Coding Club NITJ Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls', namespace='authenticate')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tag/(?P<slug>[\w-]+)/$', PostListView.as_view(), name='tagged'),
    path('startup/', include('startup.urls', namespace='startup')),
    path('codearena/', include('codearena.urls', namespace='codearena')),
    path('meeting/', include('meeting.urls', namespace='meeting')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	tags = TaggableManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	created = models.DateTimeField(default=timezone.now)
	Parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return self.body

blog/forms.py
from django import forms
from .models import Comment, Post
from pagedown.widgets import PagedownWidget


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

	body = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Comment'}))
    

class PostForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Post
        fields = ('title', 'content', 'tags',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.shortcuts import redirect
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.urls import reverse, reverse_lazy
from django import forms
from pagedown.widgets import PagedownWidget
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.dates import MonthArchiveView
import datetime

def is_valid_queryparam(param):
    return param != '' and param is not None

def home(request):
    posts = Post.objects.all()
    tag_search = request.GET.get('tag_search')
    common_tags = Post.tags.most_common()[:4]

    if is_valid_queryparam(tag_search):
        posts = posts.filter(tags__slug=tag_search)

    posts = posts[::-1]
    recent_posts = posts[:4]

    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'common_tags': common_tags,
        'recent_posts': recent_posts,
    }
    return render(request, 'blog/home.html', context)

class PostListView2(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4

class PostListView(ListView):
    model = Post
    template_name = 'blog/home2.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get('slug'))


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

'''
class PostDetailView(DetailView):
    model = Post
'''

def post_detail(request, pk):
    object = get_object_or_404(Post, pk=pk)
    comments = object.comments.filter(Parent__isnull=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            Parent_obj = None
            try:
                Parent_id = int(request.POST.get('Parent_id'))
            except:
                Parent_id = None
            if Parent_id:
                Parent_obj = Comment.objects.get(id=Parent_id)
                if Parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.Parent = Parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.post = object
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:post-detail', object.id)
            
    else:
        comment_form = CommentForm()


    return render(request, 'blog/post_detail.html', {'object': object, 'comments': comments, 'comment_form': comment_form})

'''
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:home')


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
'''

@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    common_tags = Post.tags.most_common()[:4]
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        form.save_m2m()
        # message success
        #messages.success(request, "Successfully Created")
        return redirect('blog:home')
    context = {
        "form": form,
        "common_tags": common_tags,
    }
    return render(request, "blog/post_form.html", context)

def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    # Filter posts by tag name  
    posts = Post.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'posts':posts,
    }
    return render(request, "blog/home.html", context)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

'''
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
'''

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:home')

blog/templates/blog/base2.html
{% load static %}

<!DOCTYPE html>
<html>
<head><meta name="generator" content="Hexo 3.9.0">
  <meta charset="utf-8">
  
  {% if title %}
    <title>ITALIENS - {{ title }}</title>
  {% else %}
    <title>ITALIENS</title>
  {% endif %}
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  
  
  
<meta property="og:type" content="website">
<meta property="og:title" content="ItAliens">
<meta property="og:url" content="https://italiens.org/index.html">
<meta property="og:site_name" content="ItAliens">
<meta property="og:locale" content="English">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="ItAliens">
  
    <link rel="alternate" href="/atom.xml" title="ItAliens" type="application/atom+xml">
  
  <link rel="icon" href="{% static 'blog/css/images/favicon.ico' %}">
  
    <link href="//fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Montserrat:700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic" rel="stylesheet" type="text/css">
  <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <style type="text/css">
    @font-face{font-family:futura-pt;src:url(https://use.typekit.net/af/9749f0/00000000000000000001008f/27/l?subset_id=2&fvd=n5) format("woff2");font-weight:500;font-style:normal;}
    @font-face{font-family:futura-pt;src:url(https://use.typekit.net/af/90cf9f/000000000000000000010091/27/l?subset_id=2&fvd=n7) format("woff2");font-weight:500;font-style:normal;}
    @font-face{font-family:futura-pt;src:url(https://use.typekit.net/af/8a5494/000000000000000000013365/27/l?subset_id=2&fvd=n4) format("woff2");font-weight:lighter;font-style:normal;}
    @font-face{font-family:futura-pt;src:url(https://use.typekit.net/af/d337d8/000000000000000000010095/27/l?subset_id=2&fvd=i4) format("woff2");font-weight:400;font-style:italic;}</style>
    
  <link rel="stylesheet" id="athemes-headings-fonts-css" href="//fonts.googleapis.com/css?family=Yanone+Kaffeesatz%3A200%2C300%2C400%2C700&amp;ver=4.6.1" type="text/css" media="all">

  <link rel="stylesheet" id="athemes-headings-fonts-css" href="//fonts.googleapis.com/css?family=Oswald%3A300%2C400%2C700&amp;ver=4.6.1" type="text/css" media="all">
  <link rel="stylesheet" href="{% static '/css/style.css' %}">

  <script src="{% static 'blog/js/jquery-3.1.1.min.js' %}"></script>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/fashion.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/glyphs.css' %}">

{% block head %}{% endblock head %}
</head>

<body>

  <div class="container">

    <!-- Header Starts -->

    <header id="allheader" class="site-header" role="banner">
  <div class="clearfix container">
      <div class="site-branding">

          <h1 class="site-title">
            
              <a href="/" title="ItAliens" rel="home"> ItAliens </a>             
          </h1>
          
          
            
          <nav id="main-navigation" class="main-navigation" role="navigation">
            <a class="nav-open">Menu</a>
            <a class="nav-close">Close</a>

            <div class="clearfix sf-menu">
              <ul id="main-nav" class="menu sf-js-enabled sf-arrows"  style="touch-action: pan-y;">
                    
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'blog:home' %}">Home</a> </li>
            {% if user.is_authenticated %}
                    
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'blog:post-create' %}">Create Post</a> </li>
                    
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'profile' %}">Profile</a> </li>
                    
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'logout' %}">Logout</a> </li>
            {% else %}
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'login' %}">Login</a> </li>
                    
                      <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1663"> <a class="" href="{% url 'register' %}">Register</a> </li>
            {% endif %}
              </ul>
            </div>
          </nav>

      </div>
  </div>
</header>

  <!-- Header Ends -->


    <div class="row">
      
      <div class="col-md-8">

        <h1></h1>
        <section id="main">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="">
          {% block content %}{% endblock %}
        </div>
    </section>
        
      </div> <!-- col-md-8 -->

      <div class="col-md-4">

        <h1></h1>

        <!-- search bar -->
        <!--
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
          <input type="text" name="tag_search" class="form-control" id="" aria-describedby="" placeholder="Enter tag to Search">
          </div>
          <button type="submit" class="btn btn-primary">Search</button>
        </form>-->

        <form>
  <div class="form-group">
    <input type="text" name="tag_search" class="form-control" id="" aria-describedby="" placeholder="Enter tag to search">
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
</form>

<br>
<!-- Social -->
  <div class="widget-wrap">
    <h3 class="widget-title">Connect With Us</h3>
    <div class="widget widget_athemes_social_icons">

      {% block social %}
      {% endblock social %}
      <!--<ul class="clearfix widget-social-icons">   
      
        <li><a href="https://github.com/zimo117" title="Github"><i class="fa fa-github" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Weibo"><i class="fa fa-weibo" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li> 

      
        <li><a href="https://www.facebook.com/ItAliens-557638164768269/?ref=br_rs" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Google-plus"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li> 

      
      </ul>-->
</div>
</div>
<br>
    
  <div class="widget_athemes_tabs">
    <ul id="widget-tab" class="clearfix widget-tab-nav">
      <li class="active"><a>Recent Posts</a></li>
    </ul>
    <div class="widget">
      {% block recent_posts %}
      {% endblock recent_posts %}
      <!--<ul>
        
          <li class="clearfix">

            
              <div class="widget-entry-summary" style="margin: 0;">
            

              <h6 style="margin: 0;"><a href="/2019/08/12/spid/">E Tu, Hai Fatto Lo SPID?</a></h6>
              <span>August 12, 2019</span>
            </div>

          </li>
        
      </ul>-->
    </div>
  </div>


  <div class="widget-wrap">
    <h3 class="widget-title">Most Common Tags</h3>
    <div class="widget">
      {% block common_tags %}
      {% endblock common_tags %}

      <!--<ul class="tag-list"><li class="tag-list-item"><a class="tag-list-link" href="/tags/Burocrazia/">Burocrazia</a><span class="tag-list-count">1</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/Expat/">Expat</a><span class="tag-list-count">1</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/Italy/">Italy</a><span class="tag-list-count">1</span></li><li class="tag-list-item"><a class="tag-list-link" href="/tags/London/">London</a><span class="tag-list-count">1</span></li></ul>-->
    </div>
  </div>


  
<!--    
  <div class="widget-wrap">
    <h3 class="widget-title">Tag Cloud</h3>
    <div class="widget tagcloud">
      <a href="/tags/Burocrazia/" style="font-size: 10px;">Burocrazia</a> <a href="/tags/Expat/" style="font-size: 10px;">Expat</a> <a href="/tags/Italy/" style="font-size: 10px;">Italy</a> <a href="/tags/London/" style="font-size: 10px;">London</a>
    </div>
  </div>
  -->

  <div class="widget-wrap">
    <h3 class="widget-title">Archives</h3>

    <div class="widget">
      {% block archieves %}
      {% endblock archieves %}
      <!--<ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/archives/2019/08/">August 2019</a><span class="archive-list-count">1</span></li></ul>-->
    </div>
  </div>

        
      </div> <!-- col-md-4 -->

    </div> <!-- row -->
    
  </div> <!-- container -->

<footer id="footer" class="site-footer">

  <!--<div class="widget-wrap">
    <div class="widget widget_athemes_social_icons container">

      <ul class="clearfix widget-social-icons">   
      
        <li><a href="https://github.com/zimo117" title="Github"><i class="fa fa-github" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Weibo"><i class="fa fa-weibo" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li> 

      
        <li><a href="https://www.facebook.com/ItAliens-557638164768269/?ref=br_rs" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Google-plus"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li> 

      
        <li><a href="" title="Instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li> 

      
      </ul>


      
    </div>
  </div>
-->
  <div class="clearfix container">
      <div class="site-info">
        &copy; 2019 ItAliens All Rights Reserved.
        
      </div>
      <div class="site-credit">
        Developed by <a href="https://linktr.ee/_priyanshu_panwar" target="_blank">Priyanshu</a>
      </div>
  </div>
</footer>


<!-- min height -->

<script>
    var wrapdiv = document.getElementById("wrap");
    var contentdiv = document.getElementById("content");

    wrapdiv.style.minHeight = document.body.offsetHeight - document.getElementById("allheader").offsetHeight - document.getElementById("footer").offsetHeight + "px";
    contentdiv.style.minHeight = document.body.offsetHeight - document.getElementById("allheader").offsetHeight - document.getElementById("footer").offsetHeight + "px";


    <!-- headerblur min height -->
    

</script>

    

<!-- mathjax config similar to math.stackexchange -->

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
</script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for(i=0; i < all.length; i += 1) {
            all[i].SourceElement().parentNode.className += ' has-jax';
        }
    });
</script>

<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  <link rel="stylesheet" href="{% static 'blog/fancybox/jquery.fancybox.css' %}">
  <script src="{% static 'blog/fancybox/jquery.fancybox.pack.js' %}"></script>


<script src="{% static 'blog/js/script.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
<script src="{% static 'blog/js/main.js' %}"></script>

  </div>

  <a id="rocket" href="#top" class=""></a>
  <script type="text/javascript" src="{% static 'blog/js/totop.js' %}" async=""></script>







<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
    })
})
</script>

<script src="/static/js/tagsinut.js"></script>
    <script>
    $("#post-form").submit(function(e){
        e.preventDefault();
        });</script>



<script>
    // toggle month
    var toggleMonth = function(month) {
        $(month).children('.events').slideToggle('slow');
        $(month).find('.month-data div.collapsed').toggle();
        $(month).find('.month-data div.expanded').toggle(); 
    }

    // expand the current month
    toggleMonth($('#{{now.year}}-{{now.month}}'));
    
    // intercept click to toggle month
    $('.month-data').click(function() {
        var month = $(this).parent();
        toggleMonth(month);
    });
</script>



</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
<div class="row">
  <div class="col-md-8" style="padding-top: 150px;">
  <h1>Recent Posts</h1>
  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content content-markdown">{{ post.content }}</p>
      </div>
    </article><hr>

      {% for tag in post.tags.all %}
        <p class="mr-1 badge badge-info">#{{ tag }}</p>
      {% endfor %}
      <hr>
  {% endfor %}</div>

<div class="col-md-4" style="padding-top: 150px;">
<h3>Most Common Tags</h3>
  {% for tag in common_tags %}
<ul class="tag-list"><li><a href="{% url 'tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a></li></ul>
{% endfor %}
</div>

{% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "blog/home2.html" %}

{% block content %}

{% for da in date_list %}
<p>{{ da|date:"F" }}</p>
{% endfor %}

<ul>
    {% for article in object_list %}
        <li>{{ article.date_posted|date:"F j, Y" }}:<a href="{% url 'blog:post-detail' article.id %}"> {{ article.title }}</a></li>
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Previous Month: {{ previous_month|date:"F Y" }}
    {% endif %}
    {% if next_month %}
        Next Month: {{ next_month|date:"F Y" }}
    {% endif %}
</p>
<br><br><br>
<br><br><br>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container" style="padding-top: 150px;">
  <article class="media content-section">
    <img class="rounded-circle article-img" style="width: 75px; height: 75px;" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content content-markdown">{{ object.content }}</p>
      {% for tag in post.tags.all %}
        <p class="mr-1 badge badge-info">#{{ tag }}</p>
      {% endfor %}
    </div>

  </article>
    {% if user.is_authenticated %}
      <h3>Add comment</h3>
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button class="btn btn-outline-info" type="submit">Add comment</button>
      </form>
    {% endif %}
<hr>
    {% for comment in comments %}
    <article class="media content-section">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ comment.author }}</a>
        <small class="text-muted">{{ comment.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ comment.body | linebreaks }}</p>
</div></article>
      {% for reply in comment.replies.all %}
      <article class="media content-section" style="margin-left: 20px;">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ reply.author }}</a>
        <small class="text-muted">{{ reply.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ reply.body | linebreaks }}</p>
</div></article>{% endfor %}

      {% if user.is_authenticated %}
      <div style="margin-left: 20px;">
      <h3>Reply</h3>
      
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="hidden" name="Parent_id", value="{{ comment.id }}">
        <button class="btn btn-outline-info" type="submit">Reply</button>
      </form>
    </div>
      {% endif %}
<hr>
    {% empty %}
    <p>There are no comments...</p>
    {% endfor %}
{% endblock content %}