authenticate/urls.py
from django.urls import path, include
from . import views

app_name = 'authenticate'
urlpatterns = [
    path('profile/', views.profile, name='home'),
    #path('edit/', views.profile_edit, name='profile_edit'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    #path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostListView2,
    #PostDetailView,
    #PostCreateView,
    PostUpdateView,
    #PostDeleteView,
    UserPostListView,
)
from . import views
import re

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    #path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    #path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    #path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

codingclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import PostListView


admin.site.site_header = "Coding Club NITJ"
admin.site.site_title = "Coding Club NITJ Portal"
admin.site.index_title = "Welcome to Coding Club NITJ Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls', namespace='authenticate')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tag/(?P<slug>[\w-]+)/$', PostListView.as_view(), name='tagged'),
    path('startup/', include('startup.urls', namespace='startup')),
    path('codearena/', include('codearena.urls', namespace='codearena')),
    path('meeting/', include('meeting.urls', namespace='meeting')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
	path('', views.home, name='home'),
	path('contact/', views.contact, name='contact'),
	path('subscribe/', views.subscription, name='subscribe'),
	path('team/', views.team, name='team'),
	path('dsc/', views.dsc, name='dsc'),
	path('events/', views.events, name='events'),
]

meeting/urls.py
from django.urls import path
from . import views

app_name = 'meeting'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),    
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('add/', views.add_question, name='add'),
]

core/models.py
from django.db import models

class Contact(models.Model):
	name = models.CharField(max_length=30)
	email = models.EmailField()
	subject = models.CharField(max_length=30, null=True, blank=True)
	message = models.CharField(max_length=1000)

	def __str__(self):
		return self.name

class TeamMember(models.Model):
	name = models.CharField(max_length=30)
	post = models.CharField(max_length=30)
	profile_pic = models.ImageField(upload_to='profile_pic', null=True, blank=True)
	facebook = models.URLField(null=True, blank=True)
	linkedin = models.URLField(null=True, blank=True)
	github = models.URLField(null=True, blank=True)
	
	def __str__(self):
		return self.name

class Event(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField()
	image = models.ImageField(upload_to='events')

	def __str__(self):
		return self.name

core/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(
		max_length=30,
		label="",
		widget=forms.TextInput(
				attrs={
					'name': 'name',
					'placeholder': 'Full Name',
					'class': 'form-control'
				}
			)
		)

	email = forms.EmailField(
		max_length=254,
		label="",
		widget=forms.EmailInput(
				attrs={
					'name': 'email',
					'placeholder': 'Email Address',
					'class': 'form-control'

				}
			)
		)

	subject = forms.CharField(
		max_length=100,
		label="",
		widget=forms.TextInput(
				attrs={
					'name': 'subject',
					'placeholder': 'Subject',
					'class': 'form-control'
				}
			)
		)

	message = forms.CharField(
		max_length=1000,
		label="",
		widget=forms.Textarea(
				attrs={
					'name': 'message',
					'placeholder': 'Message',
					'class': 'form-control'
				}
			)
		)


class SubscriptionForm(forms.Form):
	email = forms.EmailField(
		max_length=254,
		label="",
		widget=forms.EmailInput(
				attrs={
					'name': 'email',
					'placeholder': 'Email Address',
					'class': 'form-control'

				}
			)
		)

core/views.py
from django.shortcuts import render
from .models import Contact, TeamMember, Event
from .forms import ContactForm, SubscriptionForm
from newsletter.models import NewsletterUsers

def dsc(request):
	return render(request, 'core/dsc.html')

def events(request):
	events_done = Event.objects.all()
	return render(request, 'core/events.html', {'events_done': events_done,})


def team(request):
	members = TeamMember.objects.all()
	return render(request, 'core/team.html', {'members': members,})

def home(request):
	form = ContactForm()
	u_form = SubscriptionForm()
	context = {
		'form': form,
		'u_form': u_form,
	}
	
	return render(request, 'core/index.html', context)

def subscription(request):
	if request.method == 'POST':
		form = SubscriptionForm(request.POST)
		if form.is_valid():
			sub = NewsletterUsers()
			sub.email = form.cleaned_data['email']
			sub.save()
			context = {'form': SubscriptionForm()}
			return render(request, 'core/thanks.html', context)
	else:
		form = SubscriptionForm()
	return render(request, 'core/index.html', {'form': form })

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			con = Contact()
			con.name = form.cleaned_data['name']
			con.email = form.cleaned_data['email']
			con.subject = form.cleaned_data['subject']
			con.message = form.cleaned_data['message']
			con.save()
			context = {'form': ContactForm()}
			return render(request, 'core/thanks2.html', context)
	else:
		form = ContactForm()

	return render(request, 'core/index.html', {'form': form})

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Coding Club NITJ</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/dsc.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
<!-- Preloader Materialize CSS links-->

<!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.0/css/materialize.min.css">



        
  <!-- =======================================================
    Theme Name: Rapid
    Theme URL: https://bootstrapmade.com/rapid-multipurpose-bootstrap-business-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
 
</head>

<body>
    
    <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
  
        <div class="spinner-layer spinner-red">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
  
        <div class="spinner-layer spinner-yellow">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
  
        <div class="spinner-layer spinner-green">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div><div class="gap-patch">
            <div class="circle"></div>
          </div><div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
          
  <!--==========================
  Header
  ============================-->
  <header id="header">

    <div id="topbar">
      <div class="container">
        <div class="social-links">
          <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
          <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
          <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
          <a href="#" class="instagram"><i class="fa fa-github"></i></a>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <h1 class="text-light"><a href="{% url 'core:home' %}" class="scrollto"><span>Coding club nitj</span></a></h1>
        <!-- <a href="#header" class="scrollto"><img src="img/logo.png" alt="" class="img-fluid"></a> -->
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="core:home">Home</a></li>
          <li><a href="{% url 'blog:home' %}">Blog</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'authenticate:logout' %}">Logout</a></li>
          <li><a href="{% url 'authenticate:home' %}">Profile</a></li>
          {% else %}
          <li><a href="{% url 'authenticate:login' %}">Login</a></li>
          <li><a href="{% url 'authenticate:register' %}">Register</a></li>
          {% endif %}
          <li><a href="{% url 'core:events' %}">Events</a></li>
          <li><a href="{% url 'core:dsc' %}">DSC</a></li>
          <!--li><a href="#portfolio">Portfolio</a></li-->
          <li><a href="{% url 'core:team' %}">Team</a></li>
          <!--li class="drop-down"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="drop-down"><a href="#">Drop Down 2</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li-->
          <li><a href="#footer">Contact Us</a></li>
        </ul>
      </nav><!-- .main-nav -->
      
    </div>
  </header><!-- #header -->


  {% block content %}
  {% endblock %}

   <!--==========================
    Footer
  ============================-->
  <footer id="footer" class="section-bg">
    <div class="footer-top">
      <div class="container">

        <div class="row">

          <div class="col-lg-6">

            <div class="row">

                <div class="col-sm-6">

                  <div class="footer-info">
                    <h3>NITJ</h3>
                    <p>The National Institute of Technology is autonomous public institute of higher education in India. They are governed by Ministry of Human Resources and Development.</p>
                  </div>

                  <div class="footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Stay tuned with the latest updates from us right inside your inbox. Just drop in your Email Address.</p>
                    <form action="{% url 'core:subscribe' %}" method="post">
                      {% csrf_token %}
                       {% block u_formcontent %} {% endblock u_formcontent %}
                    </form>
                  </div>

                </div>

                <div class="col-sm-6">
                  <div class="footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                      <li><a href="#header">Home</a></li>
                      <li><a href="{% url 'meeting:index' %}">Gather Meeting</a></li>
                      <li><a href="{% url 'startup:home' %}">Ideas</a></li>
                      <li><a href="{% url 'codearena:home' %}">CodeArena</a></li>
                      <li><a href="{% url 'blog:home' %">Blog</a></li>
                    </ul>
                  </div>

                  <div class="footer-links">
                    <h4>Contact Us</h4>
                    <p>

                      Arsh Goyal <br>
                      Head, Coding Club<br>
                      <br>
                      <strong>Phone:</strong> +919914047037<br>
                      <strong>Email:</strong> codingclub@nitj.ac.in<br>
                    </p>
                  </div>

                  <div class="social-links">
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                  </div>

                </div>

            </div>

          </div>

          <div class="col-lg-6">

            <div class="form">

              <h4>Send us a message</h4>
              <!-- <p>Eos ipsa est voluptates. Nostrum nam libero ipsa vero. Debitis quasi sit eaque numquam similique commodi harum aut temporibus.</p> -->
              <form action="{% url 'core:contact' %}" method="post" role="form" class="contactForm">
                {% csrf_token %}
                <!--
                <div class="form-group fieldWrapper">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                  <div class="validation"></div>
                </div>
                -->
                {% block formcontent %}
                {% endblock %}
                <div id="sendmessage">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>

                
              </form>
            </div>

          </div>

          

        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>NITJ</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
        -->
        Developed by <a href="https://linktr.ee/_priyanshu_panwar">Priyanshu Panwar</a>|<a href="https://linktr.ee/pulkit_065">Pulkit Bhagat</a>
            </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>
  <!--Preloader Script Materialize CSS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
    })
})
</script>

<script src="/static/js/tagsinut.js"></script>
    <script>
    $("#post-form").submit(function(e){
        e.preventDefault();
        });</script>


</body>
</html>
  

core/templates/core/dsc.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="container" style="padding-top: 150px; text-align: center">

<img src="{% static 'img/logodsc.png' %}"  alt="" class="img-fluid">
<h1>DEVELOPERS STUDENT'S CLUB by GOOGLE</h1>


{% endblock content %}

core/templates/core/events.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="container" style="padding-top: 150px;">

<h1>Events</h1>
{% for member in events_done %}
<div class="row">
  <div class="col-md-6">
            <div class="member">
              <img src="{{ member.image.url }}" class="img-fluid" style="width: 3500px; height: 450px;" alt="">
            <hr>  
</div></div>
<div class="col-md-6">
	<div class="member-info">
            <div class="member-info-content" style="">
                  <h3>{{ member.name }}</h3>
                  <h5>{{ member.description }}</h5>
                </div>
              </div>
            </div><hr>
</div>
{% endfor %}
{% endblock content %}

core/templates/core/team.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<div class="container" style="padding-top: 150px;">

<h1>Team Members</h1>
{% for member in members %}
<div class="row">
  <div class="col-md-3">
            <div class="member">
              <img src="{{ member.profile_pic.url }}" class="img-fluid" style="width: 250px; height: 250px;" alt="">
            <hr>  
</div></div>
<div class="col-md-6">
	<div class="member-info">
            <div class="member-info-content" style="">
                  <h3>{{ member.name }}</h3>
                  <h5>{{ member.post }}</h5>
                  <div class="social"><h5>Social links:
                    <a href="{{ member.github }}"><i class="fa fa-github"></i></a>
                    <a href="{{ member.facebook }}"><i class="fa fa-facebook"></i></a>
                    <a href="{{ member.linkedin }}"><i class="fa fa-linkedin"></i></a>
                  </h5></div>
                </div>
              </div>
            </div><hr>
</div>
{% endfor %}
    <!--    <div class="row">

          <div class="col-lg-3 col-md-6 wow fadeInUp">
            <div class="member">
              <img src="{% static 'img/team-1.jpg' %}" class="img-fluid" style="width: 250px; height: 250px;" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Arsh Goyal</h4>
                  <span>DSC Lead</span>
                  <div class="social">
                    <a href=""><i class="fa fa-github"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="member">
              <img src="{% static 'img/team-2.jpg' %}" class="img-fluid" style="width: 250px; height: 250px;" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Aditi</h4>
                  <span>Product Manager</span>
                  <div class="social">
                    <a href=""><i class="fa fa-github"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
            <div class="member">
              <img src="{% static 'img/team-3.jpg' %}" class="img-fluid" style="width: 250px; height: 250px;" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>William Anderson</h4>
                  <span>CTO</span>
                  <div class="social">
                    <a href=""><i class="fa fa-github"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="member">
              <img src="{% static 'img/team-4.jpg' %}" class="img-fluid" style="width: 250px; height: 250px;" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Amanda Jepson</h4>
                  <span>Accountant</span>
                  <div class="social">
                    <a href=""><i class="fa fa-github"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>

</div>
-->

{% endblock content %}

core/templates/core/thanks.html
<p>We have subscribed you. <a href="{% url 'core:home' %}">Click here</a> to go to home.</p>

core/templates/core/thanks2.html
<p>We have received your query.<a href="{% url 'core:home' %}">Click here</a> to go to home.</p>