blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostListView2,
    #PostDetailView,
    #PostCreateView,
    PostUpdateView,
    #PostDeleteView,
    UserPostListView,
)
from . import views
import re

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    #path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    #path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    #path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

codearena/urls.py
from django.urls import path
from . import views

app_name = 'codearena'
urlpatterns = [
	path('', views.home, name='home'),
	path('post/<int:pk>/', views.post_detail, name='post-detail'),
]

codingclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import PostListView


admin.site.site_header = "Coding Club NITJ"
admin.site.site_title = "Coding Club NITJ Portal"
admin.site.index_title = "Welcome to Coding Club NITJ Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authenticate.urls', namespace='authenticate')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tag/(?P<slug>[\w-]+)/$', PostListView.as_view(), name='tagged'),
    path('startup/', include('startup.urls', namespace='startup')),
    path('codearena/', include('codearena.urls', namespace='codearena')),
    path('meeting/', include('meeting.urls', namespace='meeting')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codearena/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save

class Coding_Profile(models.Model):
	student = models.ForeignKey(User, on_delete=models.CASCADE)
	score = models.IntegerField(null=True, blank=True)
	events_participated = models.ManyToManyField('Event', null=True, blank=True)

	def __str__(self):
		return self.student.username

class Event(models.Model):
	title = models.CharField(max_length=100)
	date_posted = models.DateTimeField(default=timezone.now)
	date_valid = models.DateTimeField('validity date')

	def __str__(self):
		return self.title

class Question(models.Model):
	event_name = models.ForeignKey(Event, on_delete=models.CASCADE)
	text = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.text

class Solution(models.Model):
	coder = models.ForeignKey(User, on_delete=models.CASCADE)
	code = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True, blank=True)

	def __str__(self):
		return self.coder.username


def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = Coding_Profile.objects.create(student=kwargs['instance'])

post_save.connect(create_profile, sender=User)

codearena/forms.py
from django import forms
from .models import Solution

class SolutionForm(forms.ModelForm):
	class Meta:
		model = Solution
		fields = ('code',)

	code = forms.CharField(label="", max_length=2000, 
		widget=forms.Textarea(
			attrs={
			'class':'form-control', 
			'placeholder':'Code',
			}))

codearena/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Coding_Profile, Question, Event
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import SolutionForm
from django.utils import timezone

def home(request):
    posts = Event.objects.all()
    posts = posts[::-1]
    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }
    return render(request, 'codearena/home.html', context)

def post_detail(request, pk):
    object = get_object_or_404(Event, pk=pk)
    now = timezone.now
    validity = False
    if object.date_valid>=timezone.now():
    	validity = True
    if request.method == 'POST':
        comment_form = SolutionForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.coder = request.user
            new_comment.event = object
            new_comment.save()
            return render(request, 'codearena/thanks.html')
            
    else:
        comment_form = SolutionForm()

    return render(request, 'codearena/post_detail.html', {'object': object, 'comment_form': comment_form, 'validity': validity,})

codearena/templates/codearena/home.html
{% extends 'blog/base.html' %}

{% block content %}
<br>
<div class="container" style="padding-top: 120px;">
  <h1>Recent Events Ongoing</h1><hr>
  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'codearena:post-detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content content-markdown">Valid till: {{ post.date_valid|date:"F d, Y" }}</p>
      </div>
    </article>
    <hr>
    {% empty %}
    <h3>No Events yet.</h3>
  {% endfor %}

{% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

<br>
{% endblock content %}

codearena/templates/codearena/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container" style="padding-top: 150px;">
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content content-markdown">Valid till: {{ object.date_valid|date:"F d, Y" }}</p>
    </div>

  </article>
    {% if user.is_authenticated %}
    {% if validity %}
      <h3>Submit Your Code</h3>
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button class="btn btn-outline-info" type="submit">Submit Code</button>
      </form>
      {% else %}
      <h6>The event is over.</h6>
      {% endif %}

    {% endif %}
<h5>You can practice your code here before submitting:</h5>
<small>Currently, We have only Python compiler at our site. C and C++ to be available soon.</small>
  <iframe src="https://trinket.io/embed/python/1950859fc7" width="100%" height="300" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
    
<hr>
{% endblock content %}

codearena/templates/codearena/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}


{% block head %}
{{ form.media }}
{% endblock head %}


{% block content %}
    <div class="content-section container">
        <div style="padding-top: 150px;">
    <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Submit your Idea</legend>
                {{ form|crispy }}
                
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

codearena/templates/codearena/thanks.html
<h1>Your answer has been submitted.</h1>
<h4><a href="{% url 'codearena:home' %}">Click here</a> to go to CodeArena</h4>

codearena/templates/codearena/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container" style="padding-top: 150px;">
    <h1 class="mb-3">Ideas by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
<img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" style="width: 100px; height: 100px;">
    {% for post in posts %}
        <article class="media content-section">
          
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'startup:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'startup:post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}